name: Contributors
on:
  schedule:
    - cron: '0 1 * * 0' # Weekly on Sunday
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update contributors
        uses: wow-actions/contributors-list@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: 'table'
          itemsPerRow: 6
          includeBots: false
          round: true
